pull_request_rules:
- name: label scala-steward's PRs
  conditions:
  - author=scala-steward
  actions:
    label:
      add:
      - dependency-update
      remove: []
- name: merge scala-steward's PRs
  conditions:
  - author=scala-steward
  - status-success=Build and Test
  actions:
    merge:
      method: squash

- name: merge Test PRs
  conditions:
  - author=yadavan88
  - status-success=Scala CI / Build And Test
  actions:
    merge:
      method: squash
